import {
  Eye,
  Sparkles,
  ShieldCheck,
  Handshake,
  Tag,
  CalendarCheck,
  Radar,
  Network,
  Users,
  CreditCard,
  BarChart3,
  Bell,
  Percent,
  Smartphone,
  PlugZap,
  LayoutDashboard,
  CarFront,
  FileBarChart,
  Cloud,
  BrainCircuit,
  Lock,
  Layers,
  Wrench,
  Droplets,
  CircleDot,
  BatteryCharging,
  ClipboardCheck,
  Hammer,
  MessageCircle,
  History,
  TrendingUp,
  Star,
  UserPlus,
  Inbox,
  type LucideProps,
} from "lucide-react";

export const iconMap = {
  eye: Eye,
  sparkles: Sparkles,
  "shield-check": ShieldCheck,
  handshake: Handshake,
  tag: Tag,
  "calendar-check": CalendarCheck,
  radar: Radar,
  network: Network,
  users: Users,
  "credit-card": CreditCard,
  "bar-chart-3": BarChart3,
  bell: Bell,
  percent: Percent,
  smartphone: Smartphone,
  "plug-zap": PlugZap,
  "layout-dashboard": LayoutDashboard,
  "car-front": CarFront,
  "file-bar-chart": FileBarChart,
  cloud: Cloud,
  "brain-circuit": BrainCircuit,
  lock: Lock,
  layers: Layers,
  wrench: Wrench,
  droplets: Droplets,
  "circle-dot": CircleDot,
  "battery-charging": BatteryCharging,
  "clipboard-check": ClipboardCheck,
  hammer: Hammer,
  "message-circle": MessageCircle,
  history: History,
  "trending-up": TrendingUp,
  star: Star,
  "user-plus": UserPlus,
  inbox: Inbox,
} as const;

export type IconName = keyof typeof iconMap;

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Component = iconMap[name as IconName] ?? Sparkles;
  return <Component {...props} />;
}
